# Generated by Django 4.1.7 on 2024-03-07 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="title_lines",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("last_update", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Hero_Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("button_text", models.CharField(max_length=100)),
                ("last_update", models.DateTimeField(auto_now=True)),
                (
                    "Titles",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="DFS_PAGES.title_lines",
                    ),
                ),
            ],
        ),
    ]
