# Generated by Django 4.1.7 on 2024-03-07 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("DFS_PAGES", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hero_page",
            name="Titles",
        ),
        migrations.AddField(
            model_name="title_lines",
            name="placement",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="title_lines",
                to="DFS_PAGES.hero_page",
            ),
        ),
    ]
