# Generated by Django 4.1.7 on 2024-03-07 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("DFS_PAGES", "0002_remove_hero_page_titles_title_lines_placement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="title_lines",
            name="placement",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="title_lines",
                to="DFS_PAGES.hero_page",
            ),
        ),
    ]
