# Generated by Django 4.1.7 on 2024-03-07 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("DFS_PAGES", "0003_alter_title_lines_placement"),
    ]

    operations = [
        migrations.CreateModel(
            name="title_line",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("last_update", models.DateTimeField(auto_now=True)),
                (
                    "placement",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="title_lines",
                        to="DFS_PAGES.hero_page",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="title_lines",
        ),
    ]
