# Generated by Django 4.1.7 on 2024-03-07 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DFS_PAGES", "0006_aboutus_contact_faq_ourteam_testimonials"),
    ]

    operations = [
        migrations.CreateModel(
            name="Features",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("services_tag", models.CharField(max_length=100)),
                ("services_title", models.CharField(max_length=100)),
                ("services_1", models.TextField()),
                ("services_2", models.TextField()),
                ("services_3", models.TextField()),
                ("services_4", models.TextField()),
                ("services_5", models.TextField()),
                ("services_6", models.TextField()),
                ("services_image", models.ImageField(upload_to="features/")),
                ("growth_title", models.CharField(max_length=100)),
                ("growth_image", models.ImageField(upload_to="features/")),
                ("growth_tab1_name", models.CharField(max_length=100)),
                ("growth_tab1_blurb1", models.TextField()),
                ("growth_tab1_title1", models.CharField(max_length=100)),
                ("growth_tab1_blurb2", models.TextField()),
                ("growth_tab1_title2", models.CharField(max_length=100)),
                ("growth_tab1_blurb3", models.TextField()),
                ("growth_tab2_blurb1", models.TextField()),
                ("growth_tab2_title1", models.CharField(max_length=100)),
                ("growth_tab2_blurb2", models.TextField()),
                ("growth_tab2_title2", models.CharField(max_length=100)),
                ("growth_tab2_blurb3", models.TextField()),
                ("growth_tab3_blurb1", models.TextField()),
                ("growth_tab3_title1", models.CharField(max_length=100)),
                ("growth_tab3_blurb2", models.TextField()),
                ("growth_tab3_title2", models.CharField(max_length=100)),
                ("growth_tab3_blurb3", models.TextField()),
                ("tools_title", models.CharField(max_length=100)),
                ("tools_image", models.ImageField(upload_to="features/")),
                ("tools_item1", models.CharField(max_length=100)),
                ("tools_item1_blurb", models.TextField()),
                ("tools_item2", models.CharField(max_length=100)),
                ("tools_item2_blurb", models.TextField()),
                ("tools_item3", models.CharField(max_length=100)),
                ("tools_item3_blurb", models.TextField()),
                ("tools_item4", models.CharField(max_length=100)),
                ("tools_item4_blurb", models.TextField()),
                ("tools_item5", models.CharField(max_length=100)),
                ("tools_item5_blurb", models.TextField()),
                ("tools_item6", models.CharField(max_length=100)),
                ("tools_item6_blurb", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Hero",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("subtitle", models.CharField(max_length=100)),
                ("content", models.TextField(blank=True)),
                ("image", models.ImageField(upload_to="images/hero")),
                ("button", models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name="contact",
            old_name="name",
            new_name="full_name",
        ),
        migrations.RenameField(
            model_name="ourteam",
            old_name="name",
            new_name="first_name",
        ),
        migrations.RenameField(
            model_name="testimonials",
            old_name="name",
            new_name="full_name",
        ),
        migrations.RenameField(
            model_name="testimonials",
            old_name="title",
            new_name="job_title",
        ),
        migrations.RemoveField(
            model_name="aboutus",
            name="description",
        ),
        migrations.AddField(
            model_name="aboutus",
            name="button",
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name="aboutus",
            name="tag",
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name="aboutus",
            name="about",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="faq",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
