# Generated by Django 4.1.7 on 2024-03-07 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DFS_PAGES", "0007_features_hero_rename_name_contact_full_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="features",
            name="growth_tab2_name",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="features",
            name="growth_tab3_name",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="features",
            name="growth_tab1_blurb1",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="features",
            name="growth_tab1_blurb2",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="features",
            name="growth_tab1_blurb3",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="features",
            name="growth_tab1_name",
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name="features",
            name="growth_tab2_blurb1",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="features",
            name="growth_tab2_blurb2",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="features",
            name="growth_tab2_blurb3",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="features",
            name="growth_tab3_blurb1",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="features",
            name="growth_tab3_blurb2",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="features",
            name="growth_tab3_blurb3",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="features",
            name="services_1",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="features",
            name="services_2",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="features",
            name="services_3",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="features",
            name="services_4",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="features",
            name="services_5",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="features",
            name="services_6",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="features",
            name="tools_item1_blurb",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="features",
            name="tools_item2_blurb",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="features",
            name="tools_item3_blurb",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="features",
            name="tools_item4_blurb",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="features",
            name="tools_item5_blurb",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="features",
            name="tools_item6_blurb",
            field=models.CharField(max_length=500),
        ),
    ]
