# Generated by Django 4.1.7 on 2024-03-07 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "DFS_PAGES",
            "0008_features_growth_tab2_name_features_growth_tab3_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="aboutus",
            name="image",
            field=models.ImageField(upload_to=""),
        ),
        migrations.AlterField(
            model_name="features",
            name="growth_image",
            field=models.ImageField(upload_to=""),
        ),
        migrations.AlterField(
            model_name="features",
            name="services_image",
            field=models.ImageField(upload_to=""),
        ),
        migrations.AlterField(
            model_name="features",
            name="tools_image",
            field=models.ImageField(upload_to=""),
        ),
        migrations.AlterField(
            model_name="hero",
            name="image",
            field=models.ImageField(upload_to=""),
        ),
        migrations.AlterField(
            model_name="ourteam",
            name="image",
            field=models.ImageField(upload_to=""),
        ),
    ]
