# Generated by Django 4.1.7 on 2024-03-13 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DFS_PAGES", "0015_rename_topic_testimonials_company"),
    ]

    operations = [
        migrations.CreateModel(
            name="expo_form",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("email", models.CharField(max_length=100)),
                ("company", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=100)),
                ("how_heard", models.CharField(default="Expo West", max_length=100)),
                (
                    "package",
                    models.CharField(
                        choices=[
                            ("D/M Report", "Demo/Merchandising Report"),
                            ("PEA", "Promotion Efficacy Analysis"),
                        ],
                        max_length=100,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="expo_info",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("page_title", models.CharField(max_length=100)),
                ("page_subtitle", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="")),
                ("button", models.CharField(max_length=100)),
                ("video_link", models.CharField(max_length=200)),
                ("video_title", models.CharField(max_length=100)),
                ("video_subtitle", models.CharField(max_length=100)),
            ],
        ),
    ]
