# Generated by Django 4.1.7 on 2024-03-19 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DFS_PAGES", "0017_homepage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homepage",
            name="about",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="last_update",
        ),
        migrations.AddField(
            model_name="homepage",
            name="about_us",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="contact_info",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="faqs",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="features",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="hero",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="our_team",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="testimonials",
            field=models.BooleanField(default=True),
        ),
    ]
