# Generated by Django 4.1.7 on 2024-03-19 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "DFS_PAGES",
            "0018_remove_homepage_about_remove_homepage_last_update_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Services",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("services_tag", models.CharField(max_length=100)),
                ("services_title", models.CharField(max_length=100)),
                ("services_1", models.CharField(max_length=500)),
                ("services_2", models.CharField(max_length=500)),
                ("services_3", models.CharField(max_length=500)),
                ("services_4", models.CharField(max_length=500)),
                ("services_5", models.CharField(max_length=500)),
                ("services_6", models.CharField(max_length=500)),
                ("services_image", models.ImageField(upload_to="")),
            ],
        ),
        migrations.CreateModel(
            name="Solutions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("solutions_title", models.CharField(max_length=100)),
                ("solutions_image", models.ImageField(upload_to="")),
            ],
        ),
        migrations.CreateModel(
            name="solutions_item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("solutions_item", models.CharField(max_length=100)),
                ("solutions_item_blurb", models.CharField(max_length=500)),
                ("solutions_item_icon", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Tabs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tabs_title", models.CharField(max_length=100)),
                ("tabs_image", models.ImageField(upload_to="")),
                ("tabs_tab1", models.CharField(default=None, max_length=100)),
                ("tabs_tab1_text", models.CharField(max_length=500)),
                ("tabs_tab1_bullet1", models.CharField(max_length=100)),
                ("tabs_tab1_bullet_blurb1", models.CharField(max_length=500)),
                ("tabs_tab1_bullet2", models.CharField(max_length=100)),
                ("tabs_tab1_bullet_blurb2", models.CharField(max_length=500)),
                ("tabs_tab1_bullet3", models.CharField(blank=True, max_length=100)),
                (
                    "tabs_tab1_bullet_blurb3",
                    models.CharField(blank=True, max_length=500),
                ),
                ("tabs_tab2", models.CharField(default=None, max_length=100)),
                ("tabs_tab2_text", models.CharField(max_length=500)),
                ("tabs_tab2_bullet1", models.CharField(max_length=100)),
                ("tabs_tab2_bullet_blurb1", models.CharField(max_length=500)),
                ("tabs_tab2_bullet2", models.CharField(max_length=100)),
                ("tabs_tab2_bullet_blurb2", models.CharField(max_length=500)),
                ("tabs_tab2_bullet3", models.CharField(blank=True, max_length=100)),
                (
                    "tabs_tab2_bullet_blurb3",
                    models.CharField(blank=True, max_length=500),
                ),
                ("tab3", models.BooleanField(default=False)),
                ("tabs_tab3", models.CharField(default=None, max_length=100)),
                ("tabs_tab3_text", models.CharField(max_length=500)),
                ("tabs_tab3_bullet1", models.CharField(max_length=100)),
                ("tabs_tab3_bullet_blurb1", models.CharField(max_length=500)),
                ("tabs_tab3_bullet2", models.CharField(max_length=100)),
                ("tabs_tab3_bullet_blurb2", models.CharField(max_length=500)),
                ("tabs_tab3_bullet3", models.CharField(blank=True, max_length=100)),
                (
                    "tabs_tab3_bullet_blurb3",
                    models.CharField(blank=True, max_length=500),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="title_line",
            name="placement",
        ),
        migrations.DeleteModel(
            name="Pages",
        ),
        migrations.DeleteModel(
            name="title_line",
        ),
        migrations.AddField(
            model_name="solutions",
            name="solutions_items",
            field=models.ManyToManyField(
                blank=True, related_name="solutions", to="DFS_PAGES.solutions_item"
            ),
        ),
    ]
