# Generated by Django 4.1.7 on 2024-03-19 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DFS_PAGES", "0019_services_solutions_solutions_item_tabs_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="homepage",
            old_name="contact_info",
            new_name="contact",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="features",
        ),
        migrations.AddField(
            model_name="homepage",
            name="services",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="homepage",
            name="solutions",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="homepage",
            name="tabs",
            field=models.BooleanField(default=True),
        ),
    ]
